package dev.freya02.jda.emojis.old;

import net.dv8tion.jda.api.entities.emoji.UnicodeEmoji;
import net.dv8tion.jda.internal.entities.emoji.UnicodeEmojiImpl;

interface EmojiFamilyB {
	UnicodeEmoji KISS_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍💋‍👩🏽");
	
	UnicodeEmoji KISS_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍💋‍👩🏽");
	
	UnicodeEmoji KISS_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍💋‍👩🏾");
	
	UnicodeEmoji KISS_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍💋‍👩🏾");
	
	UnicodeEmoji KISS_WOMAN_WOMAN_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍💋‍👩🏿");
	
	UnicodeEmoji KISS_WOMAN_WOMAN_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍💋‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART = new UnicodeEmojiImpl("💑");
	
	UnicodeEmoji COUPLE_WITH_HEART_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("💑🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("💑🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("💑🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("💑🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_DARK_SKIN_TONE = new UnicodeEmojiImpl("💑🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_LIGHT_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("🧑🏻‍❤️‍🧑🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_LIGHT_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏻‍❤‍🧑🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("🧑🏻‍❤️‍🧑🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏻‍❤‍🧑🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("🧑🏻‍❤️‍🧑🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏻‍❤‍🧑🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_LIGHT_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("🧑🏻‍❤️‍🧑🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_LIGHT_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏻‍❤‍🧑🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_LIGHT_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("🧑🏼‍❤️‍🧑🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_LIGHT_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏼‍❤‍🧑🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("🧑🏼‍❤️‍🧑🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏼‍❤‍🧑🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("🧑🏼‍❤️‍🧑🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏼‍❤‍🧑🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_LIGHT_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("🧑🏼‍❤️‍🧑🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_LIGHT_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏼‍❤‍🧑🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("🧑🏽‍❤️‍🧑🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏽‍❤‍🧑🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("🧑🏽‍❤️‍🧑🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏽‍❤‍🧑🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("🧑🏽‍❤️‍🧑🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏽‍❤‍🧑🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("🧑🏽‍❤️‍🧑🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏽‍❤‍🧑🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_DARK_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("🧑🏾‍❤️‍🧑🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_DARK_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏾‍❤‍🧑🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("🧑🏾‍❤️‍🧑🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏾‍❤‍🧑🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("🧑🏾‍❤️‍🧑🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_DARK_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏾‍❤‍🧑🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_DARK_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("🧑🏾‍❤️‍🧑🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_MEDIUM_DARK_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏾‍❤‍🧑🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_DARK_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("🧑🏿‍❤️‍🧑🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_DARK_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏿‍❤‍🧑🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("🧑🏿‍❤️‍🧑🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏿‍❤‍🧑🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("🧑🏿‍❤️‍🧑🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_DARK_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏿‍❤‍🧑🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("🧑🏿‍❤️‍🧑🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_PERSON_PERSON_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("🧑🏿‍❤‍🧑🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN = new UnicodeEmojiImpl("👩‍❤️‍👨");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩‍❤‍👨");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_LIGHT_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_LIGHT_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_MEDIUM_DARK_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_MAN_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN = new UnicodeEmojiImpl("👨‍❤️‍👨");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨‍❤‍👨");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏻‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏻‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏻‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏻‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👨🏻‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏻‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏻‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏻‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏻‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_LIGHT_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏻‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏼‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏼‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏼‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏼‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👨🏼‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏼‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏼‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏼‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏼‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_LIGHT_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏼‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏽‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏽‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏽‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏽‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👨🏽‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏽‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏽‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏽‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏽‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏽‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏾‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏾‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏾‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏾‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👨🏾‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏾‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏾‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏾‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏾‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_MEDIUM_DARK_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏾‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏿‍❤️‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏿‍❤‍👨🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👨🏿‍❤️‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏿‍❤‍👨🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👨🏿‍❤️‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏿‍❤‍👨🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏿‍❤️‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏿‍❤‍👨🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE = new UnicodeEmojiImpl("👨🏿‍❤️‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_MAN_MAN_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👨🏿‍❤‍👨🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN = new UnicodeEmojiImpl("👩‍❤️‍👩");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩‍❤‍👩");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏻‍❤️‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_LIGHT_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏻‍❤‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏼‍❤️‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_LIGHT_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏼‍❤‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏽‍❤️‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏽‍❤‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏾‍❤️‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_MEDIUM_DARK_SKIN_TONE_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏾‍❤‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👩🏻");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_LIGHT_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👩🏼");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👩🏽");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE_MEDIUM_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👩🏾");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE = new UnicodeEmojiImpl("👩🏿‍❤️‍👩🏿");
	
	UnicodeEmoji COUPLE_WITH_HEART_WOMAN_WOMAN_DARK_SKIN_TONE_MINIMALLY_QUALIFIED = new UnicodeEmojiImpl("👩🏿‍❤‍👩🏿");
	
	UnicodeEmoji FAMILY_MAN_WOMAN_BOY = new UnicodeEmojiImpl("👨‍👩‍👦");
	
	UnicodeEmoji FAMILY_MAN_WOMAN_GIRL = new UnicodeEmojiImpl("👨‍👩‍👧");
	
	UnicodeEmoji FAMILY_MAN_WOMAN_GIRL_BOY = new UnicodeEmojiImpl("👨‍👩‍👧‍👦");
	
	UnicodeEmoji FAMILY_MAN_WOMAN_BOY_BOY = new UnicodeEmojiImpl("👨‍👩‍👦‍👦");
	
	UnicodeEmoji FAMILY_MAN_WOMAN_GIRL_GIRL = new UnicodeEmojiImpl("👨‍👩‍👧‍👧");
	
	UnicodeEmoji FAMILY_MAN_MAN_BOY = new UnicodeEmojiImpl("👨‍👨‍👦");
	
	UnicodeEmoji FAMILY_MAN_MAN_GIRL = new UnicodeEmojiImpl("👨‍👨‍👧");
	
	UnicodeEmoji FAMILY_MAN_MAN_GIRL_BOY = new UnicodeEmojiImpl("👨‍👨‍👧‍👦");
	
	UnicodeEmoji FAMILY_MAN_MAN_BOY_BOY = new UnicodeEmojiImpl("👨‍👨‍👦‍👦");
	
	UnicodeEmoji FAMILY_MAN_MAN_GIRL_GIRL = new UnicodeEmojiImpl("👨‍👨‍👧‍👧");
	
	UnicodeEmoji FAMILY_WOMAN_WOMAN_BOY = new UnicodeEmojiImpl("👩‍👩‍👦");
	
	UnicodeEmoji FAMILY_WOMAN_WOMAN_GIRL = new UnicodeEmojiImpl("👩‍👩‍👧");
	
	UnicodeEmoji FAMILY_WOMAN_WOMAN_GIRL_BOY = new UnicodeEmojiImpl("👩‍👩‍👧‍👦");
	
	UnicodeEmoji FAMILY_WOMAN_WOMAN_BOY_BOY = new UnicodeEmojiImpl("👩‍👩‍👦‍👦");
	
	UnicodeEmoji FAMILY_WOMAN_WOMAN_GIRL_GIRL = new UnicodeEmojiImpl("👩‍👩‍👧‍👧");
	
	UnicodeEmoji FAMILY_MAN_BOY = new UnicodeEmojiImpl("👨‍👦");
	
	UnicodeEmoji FAMILY_MAN_BOY_BOY = new UnicodeEmojiImpl("👨‍👦‍👦");
	
	UnicodeEmoji FAMILY_MAN_GIRL = new UnicodeEmojiImpl("👨‍👧");
	
	UnicodeEmoji FAMILY_MAN_GIRL_BOY = new UnicodeEmojiImpl("👨‍👧‍👦");
	
	UnicodeEmoji FAMILY_MAN_GIRL_GIRL = new UnicodeEmojiImpl("👨‍👧‍👧");
	
	UnicodeEmoji FAMILY_WOMAN_BOY = new UnicodeEmojiImpl("👩‍👦");
	
	UnicodeEmoji FAMILY_WOMAN_BOY_BOY = new UnicodeEmojiImpl("👩‍👦‍👦");
	
	UnicodeEmoji FAMILY_WOMAN_GIRL = new UnicodeEmojiImpl("👩‍👧");
	
	UnicodeEmoji FAMILY_WOMAN_GIRL_BOY = new UnicodeEmojiImpl("👩‍👧‍👦");
	
	UnicodeEmoji FAMILY_WOMAN_GIRL_GIRL = new UnicodeEmojiImpl("👩‍👧‍👧");
	
	
}
